const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },{
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 마르게리따',
        summary:'신선한 재료의 산뜻한 풍미',
        price:5500,
        sale:20,
        review:17,
    },{
        src: './images/kurly_003.jpg',
        name: '[샐러디] 썸머 시그니처 그릴드 치킨 샐러드',
        summary: '신선한 채소와 부드러운 닭가슴살의 만남',
        price: 8900,
        sale: 10,
        review: 85,
    },
    {
        src: './images/kurly_004.jpg',
        name: '[워터플러스] 여름 한정 과일 탄산수 3종',
        summary: '청량한 과일향으로 수분 보충!',
        price: 4200,
        sale: 15,
        review: 67,
    },
    {
        src: './images/kurly_005.jpg',
        name: '[오설록] 아이스 그린티 라떼 파우치',
        summary: '여름에 즐기는 차가운 녹차의 진한 풍미',
        price: 7200,
        sale: 5,
        review: 102,
    },
    {
        src: './images/kurly_006.jpg',
        name: '[프레시지] 냉모밀 밀키트',
        summary: '한여름 집에서도 시원한 냉모밀 한 그릇',
        price: 6500,
        sale: 12,
        review: 46,
    },
    {
        src: './images/kurly_007.jpg',
        name: '[제주네이처] 생감귤주스 100%',
        summary: '제주 햇감귤로 만든 여름의 맛',
        price: 4800,
        sale: 8,
        review: 58,
    },
    {
        src: './images/kurly_008.jpg',
        name: '[쿠캣마켓] 아이스 군고구마 바',
        summary: '차갑게 즐기는 달콤한 고구마 스낵',
        price: 3300,
        sale: 10,
        review: 39,
    },
    {
        src: './images/kurly_009.jpg',
        name: '[비비고] 여름 한정 냉쫄면 세트',
        summary: '탱글탱글한 면발과 시원한 육수의 조화',
        price: 5600,
        sale: 18,
        review: 71,
    },
    {
        src: './images/kurly_010.jpg',
        name: '[샘표] 냉국수 간장 소스 세트',
        summary: '집에서도 간편하게 시원한 냉국수',
        price: 3900,
        sale: 6,
        review: 33,
    },
    {
        src: './images/kurly_011.jpg',
        name: '[달콤] 디카페인 아이스 콜드브루',
        summary: '잠 못 드는 여름밤, 카페인 부담 없이',
        price: 5100,
        sale: 9,
        review: 45,
    },
    {
        src: './images/kurly_012.jpg',
        name: '[농심] 여름 특선 멀티팩 과일 젤리 5종',
        summary: '간편하게 즐기는 시원한 젤리 간식',
        price: 3800,
        sale: 11,
        review: 61,
    },    
]